require("shared/constants")
require("shared/molecules")
require("shared/buildings")
require("control/entity")
require("control/gui")

script.on_init(function()
	entity_on_init()
	gui_on_init()
end)
script.on_event(defines.events.on_tick, function(event_data)
	entity_on_tick(event_data)
	gui_on_tick(event_data)
end)
