require("shared/constants")
require("shared/molecules")
require("shared/buildings")
require("control/entity")
require("control/gui")

script.on_init(function()
	entity_on_init()
	gui_on_init()
end)
script.on_nth_tick(10, function(event_data)
	entity_on_nth_tick(event_data)
	gui_on_nth_tick(event_data)
end)
