MOLECULES_GROUP_NAME = "molecules"
MOLECULE_REACTION_NAME = "molecule-reaction"
ATOM_ITEM_PREFIX = "atom-"
MOLECULE_ITEM_PREFIX = "molecule-"
BASE_NAME = "base"
CATALYST_NAME = "catalyst"
MODIFIER_NAME = "modifier"
RESULT_NAME = "result"
BONUS_NAME = "bonus"
REMAINDER_NAME = "remainder"
MOLECULE_REACTION_COMPONENT_NAMES = {BASE_NAME, CATALYST_NAME, MODIFIER_NAME, RESULT_NAME, BONUS_NAME, REMAINDER_NAME}
MOLECULE_REACTION_REACTANT_NAMES = {BASE_NAME, CATALYST_NAME, MODIFIER_NAME}
MOLECULE_REACTION_COMPONENT_OFFSETS = {
	[BASE_NAME] = {x = -1, y = 1},
	[CATALYST_NAME] = {x = 0, y = 1},
	[MODIFIER_NAME] = {x = 1, y = 1},
	[RESULT_NAME] = {x = -1, y = -1},
	[BONUS_NAME] = {x = 0, y = -1},
	[REMAINDER_NAME] = {x = 1, y = -1},
}
MOLECULE_REACTION_REACTANTS_NAME = MOLECULE_REACTION_NAME.."-reactants"
MOLECULE_REACTION_SELECTOR_PREFIX = MOLECULE_REACTION_NAME.."-selector-"
MOLECULE_REACTION_SELECTOR_REACTANTS = {BASE_NAME, MODIFIER_NAME}
ROTATION_SELECTOR_NAME = "rotation"
TARGET_SELECTOR_NAME = "target"
